### ISSUE TITLE
Converter pointing to missing Pulumi repository?

### ISSUE THREAD

**Issue by undervane** [pulumi/pulumi-converter-terraform#118]
### What happened?

New installation of Pulumi, followed to onboarding guide from [here](https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform/#converting-terraform-hcl-to-pulumi). Triggered `pulumi convert --from terraform --language typescript` and got this error.

### Example

```warning: failed to install provider "helm": could not find latest version for provider helm: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-helm/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens```

### Output of `pulumi about`

```
CLI          
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Host     
OS       darwin
Version  13.6.3
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal
```

### Additional context

I also had the rate limiter issue which I did overcome by using a Github token so I don't include this as part of the reproduction

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @undervane. Thanks for opening the issue and sorry for the trouble. The reason you're getting this error is because there isn't a Pulumi version of the Terraform helm provider and we haven't added the capability of translating from Terraform helm resources to the Pulumi Kubernetes provider's helm resources.

You may be able to workaround this by commenting out the helm TF code, doing the conversion, and then manually updating the converted code to use the Kubernetes Helm [Release](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/) resource.

We have an existing issue tracking adding support for automatically doing this conversion: https://github.com/pulumi/pulumi-converter-terraform/issues/58. I'm going to close this issue as a duplicate.

**Comment by Frassle** [comment]
> You may be able to workaround this by commenting out the helm TF code, doing the conversion, and then manually updating the converted code to use the Kubernetes Helm [Release](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/) resource.

Note this is only a warning not an error. The converter makes a best guess of how to translate the helm resources, you can let it write those out then just fix them to point to the real resources from the k8s provider.
